app = "atlos-platform-staging"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "staging.atlos.org"
  PORT = "8080"
  S3_BUCKET = "atlos-content-dev"
  AWS_REGION = "us-east-1"
  APPSIGNAL_APP_ENV = "staging"
  ENVIRONMENT = "staging"
  ENABLE_CAPTCHAS = "false"
  INSTANCE_NAME = "staging"
  ECTO_IPV6 = "true"
  ERL_AFLAGS = "-proto_dist inet6_tcp"
  ONBOARDING_PROJECT_ID = "deb6c474-34f1-47ab-a3b5-3928548178c3"
  ATTRIBUTE_OPTIONS = """
    {
      "type": [
        "Civilian Harm"
      ],
      "impact": [
        "Residential",
        "Industrial",
        "Administrative",
        "Healthcare",
        "School or childcare",
        "Military",
        "Undefined",
        "Commercial",
        "Religious",
        "Cultural",
        "Roads/Highways/Transport",
        "Humanitarian",
        "Food/Food Infrastructure"
      ],
      "equipment": [
        "Unknown",
        "HE rocket artillery",
        "HE artillery inc mortars",
        "Cluster munitions",
        "Incendiary munitions",
        "Cruise missile",
        "Ballistic missile",
        "Thermobaric munition",
        "Vehicle mounted weapon",
        "Small arms",
        "Air strike",
        "Land mines",
        "Anti-air missile",
        "Loitering munition"
      ]
    }
  """
  AUTOTAG_USER_INCIDENTS = "[\"Volunteer\"]"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
